name: Build

on: [push]

env:
  CUDA_BIN: /usr/local/cuda/bin

jobs:
  build:
    name: ${{ matrix.os }} (${{ matrix.config }}) ${{ matrix.cuda }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        config: [Release, Debug]
        cuda: [cuda, '']

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt remove --purge cmake
        sudo snap install cmake --classic
        sudo apt update
        sudo apt install \
                          libarmadillo-dev \
                          libeigen3-dev \
                          libcgal-dev \
                          libsuitesparse-dev \
                          libopenblas-dev \
                          libglew-dev \
                          libglfw3-dev \
                          cimg-dev

    - name: Install Cuda
      if: matrix.cuda == 'cuda'
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
        sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
        sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub
        sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
        sudo apt-get update
        sudo apt-get -y install cuda

    - name: Install Embree
      run: |
				tar xzf embree-4.0.1.x86_64.linux.tar.gz
				source embree-4.0.1.x86_64.linux/embree-vars.sh

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: |
        export PATH=${CUDA_BIN}:${PATH}
        source /opt/intel/oneapi/setvars.sh
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.config}}

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        source /opt/intel/oneapi/setvars.sh
        cmake --build . --config ${{matrix.config}}
